# Generated by Django 6.0.4 on 2026-04-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "CustomUser",
                "verbose_name_plural": "CustomUsers",
            },
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="phote",
            new_name="photo",
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="CustomUser",
        ),
    ]
