# Generated by Django 6.0.4 on 2026-04-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/"),
        ),
    ]
