# Generated by Django 5.0.1 on 2026-04-02 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=450)),
                ("description", models.TextField()),
                ("deadline", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("hali bajarilmagan", "Hali bajarilmagan"),
                            ("bajarilmoqda", "Bajarilmoqda"),
                            ("bajarilgan", "Bajarilgan"),
                        ],
                        max_length=400,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vazifa",
                "verbose_name_plural": "Vazifalar",
            },
        ),
    ]
