# Generated by Django 6.0.3 on 2026-04-05 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_name", models.CharField(max_length=300)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("backend", "BACKEND"),
                            ("frontend", "FRONTEND"),
                            ("mobile", "MOBILE"),
                        ],
                        max_length=200,
                    ),
                ),
                ("start_date", models.DateField()),
                ("finish_date", models.DateField()),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "Group",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Familiya"),
                ),
                ("age", models.IntegerField()),
                ("phone", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "db_table": "Student",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="Familiya"),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("backend", "BACKEND"),
                            ("frontend", "FRONTEND"),
                            ("mobile", "MOBILE"),
                        ]
                    ),
                ),
                ("experience", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
                "db_table": "Teacher",
            },
        ),
        migrations.CreateModel(
            name="GroupStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="erp.group"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="erp.student"
                    ),
                ),
            ],
            options={
                "db_table": "Group_students",
            },
        ),
        migrations.AddField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="erp.teacher"
            ),
        ),
    ]
