# Generated by Django 6.0.3 on 2026-04-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.teacher"
            ),
        ),
        migrations.AlterField(
            model_name="groupstudents",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.group"
            ),
        ),
        migrations.AlterField(
            model_name="groupstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="erp.student"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="subject",
            field=models.CharField(
                choices=[
                    ("backend", "BACKEND"),
                    ("frontend", "FRONTEND"),
                    ("mobile", "MOBILE"),
                ],
                max_length=200,
            ),
        ),
    ]
